# Generated by Django 3.0.6 on 2021-08-13 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default=None, max_length=10)),
                ('serial_num', models.CharField(max_length=10)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('class_code', models.CharField(max_length=30)),
                ('class_order', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.PositiveIntegerField(default=None)),
                ('identification_code', models.CharField(max_length=30)),
                ('half_year', models.CharField(max_length=10)),
                ('required', models.CharField(max_length=10)),
                ('registration_type', models.PositiveIntegerField(default=None)),
                ('time', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=40)),
                ('total_num', models.IntegerField(default=0)),
                ('ntu_num', models.IntegerField(default=0)),
                ('external_num', models.IntegerField(default=0)),
                ('constraints', models.CharField(max_length=300)),
                ('remark', models.CharField(max_length=300)),
                ('class_url', models.URLField(default=None)),
                ('course_introduction', models.TextField(default=None)),
                ('course_goal', models.TextField(default=None)),
                ('course_requirement', models.TextField(default=None)),
                ('course_reading', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('teacher_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('content', models.TextField(default=None)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(default=None)),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField(default=None)),
                ('description', models.CharField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Teacher'),
        ),
    ]
