# Generated by Django 3.0.6 on 2021-08-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_goal',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_introduction',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_reading',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_requirement',
            field=models.TextField(blank=True, default=None),
        ),
    ]
