# Generated by Django 3.0.6 on 2021-08-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20210813_1435'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('semester', 'serial_num', 'department'), name='unique course'),
        ),
    ]
